apiVersion: apps/v1
kind: Deployment
metadata:
  name: webmvc-deployment
  labels:
    app: webmvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webmvc
  template:
    metadata:
      labels:
        app: webmvc
    spec:
      containers:
        - name: webmvc
          image: aspnetcoremicroservices.azurecr.io/webmvc:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: webmvc-service
spec:
  type: NodePort
  selector:
    app: webmvc
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 80
      nodePort: 36000