apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingaggregatormobile-deployment
  labels:
    app: shoppingaggregatormobile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingaggregatormobile
  template:
    metadata:
      labels:
        app: shoppingaggregatormobile
    spec:
      containers:
        - name: shoppingaggregatormobile
          image: aspnetcoremicroservices.azurecr.io/shoppingaggregatormobile:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
             - name: ASPNETCORE_ENVIRONMENT
               value: Development
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: shoppingaggregatormobile-service
spec:
  selector:
    app: shoppingaggregatormobile
  ports:
    - protocol: TCP
      port: 80