apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderdb-deployment
  labels:
    app: orderdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderdb
  template:
    metadata:
      labels:
        app: orderdb
    spec:
      containers:
        - name: orderdb
          image: mcr.microsoft.com/mssql/server:2017-latest
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
             - name: ORDER_INITDB_ROOT_USERNAME
               valueFrom: 
                secretKeyRef:
                  name: orderdb-secret
                  key: mssql-root-username
             - name: ORDER_INITDB_ROOT_PASSWORD
               valueFrom: 
                secretKeyRef:
                  name: orderdb-secret
                  key: mssql-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: orderdb-service
spec:
  selector:
    app: orderdb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432