apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocelotapigwweb-deployment
  labels:
    app: ocelotapigwweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocelotapigwweb
  template:
    metadata:
      labels:
        app: ocelotapigwweb
    spec:
      containers:
        - name: ocelotapigwweb
          image: aspnetcoremicroservices.azurecr.io/ocelotapigwweb:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ocelotapigwweb-service
spec:
  type: NodePort
  selector:
    app: ocelotapigwweb
  ports:
    - protocol: TCP
      port: 8010
      targetPort: 80
      nodePort: 33000