apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocelotapigmobile-deployment
  labels:
    app: ocelotapigmobile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocelotapigmobile
  template:
    metadata:
      labels:
        app: ocelotapigmobile
    spec:
      containers:
        - name: ocelotapigmobile
          image: aspnetcoremicroservices.azurecr.io/ocelotapigmobile:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
             - name: ASPNETCORE_ENVIRONMENT
               value: Development
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: ocelotapigmobile-service
spec:
  selector:
    app: ocelotapigmobile
  ports:
    - protocol: TCP
      port: 80