apiVersion: apps/v1
kind: Deployment
metadata:
  name: discountdb-deployment
  labels:
    app: discountdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discountdb
  template:
    metadata:
      labels:
        app: discountdb
    spec:
      containers:
        - name: discountdb
          image: postgres
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
             - name: DISCOUNT_INITDB_ROOT_USERNAME
               valueFrom: 
                secretKeyRef:
                  name: discountdb-secret
                  key: postgres-root-username
             - name: DISCOUNT_INITDB_ROOT_PASSWORD
               valueFrom: 
                secretKeyRef:
                  name: discountdb-secret
                  key: postgres-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: discountdb-service
spec:
  selector:
    app: discountdb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432