apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingaggregatorweb-deployment
  labels:
    app: shoppingaggregatorweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingaggregatorweb
  template:
    metadata:
      labels:
        app: shoppingaggregatorweb
    spec:
      containers:
        - name: shoppingaggregatorweb
          image: aspnetcoremicroservices.azurecr.io/shoppingaggregatorweb:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: shoppingaggregatorweb-service
spec:
  type: NodePort
  selector:
    app: shoppingaggregatorweb
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 80
      nodePort: 34000