version: '3.4'

services:
  catalog.db:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  basket.db:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  discount.db:
    container_name: discountdb
    environment:
      -  POSTGRES_USER=admin
      -  POSTGRES_PASSWORD=admin1234
      -  POSTGRES_DB=DiscountDb
    restart: always
    ports:
      -  "5432:5432"
    volumes:
      -  postgres_data:/var/lib/postgresql/data/

  order.db:
    container_name: orderdb
    environment:
      SA_PASSWORD: "SwN12345678"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin 

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - portainer_data:/data

  elasticsearch:
    container_name: elasticsearch
    volumes:
        - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
        - xpack.monitoring.enabled=true
        - xpack.watcher.enabled=false
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - discovery.type=single-node
    ports:
      - 9200:9200
    networks:
      - elastic

  kibana:
   container_name: kibana
   environment:
    - ELASTICSEARCH_URL=http://localhost:9200
   ports:
    - 5601:5601
   networks:
    - elastic

  catalog.api:
    container_name: catalogapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    ports:
      - "8000:80"

  basket.api:
    container_name: basketapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
      - "GrpcSettings:DiscountUrl=http://discount.grpc"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    ports:
      - "8001:80"

  discount.api:
    container_name: discountapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234"
    ports:
      - "8002:80"

  discount.grpc:
    container_name: discountgrpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234"
    ports:
      - "8003:80"

  ordering.api:
    container_name: orderingapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:MssqlConnectionString=Server=192.168.1.68,1433;Database=OrderDb;User Id=sa;Password=SwaN12345678!!;"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    ports:
      - "8004:80"

  ocelotapigw.web:
    container_name: ocelotapigwweb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8010:80"

  ocelotapigw.mobile:
    container_name: ocelotapigwmobile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8011:80"

  shopping.aggregator.mobile:
    container_name: shoppingaggregatormobile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiSettings:CatalogUrl=http://catalog.api"
      - "ApiSettings:BasketUrl=http://basket.api"
      - "ApiSettings:OrderingUrl=http://ordering.api"
    ports:
      - "8006:80"

  shopping.aggregator.web:
    container_name: shoppingaggregatorweb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiSettings:CatalogUrl=http://catalog.api"
      - "ApiSettings:BasketUrl=http://basket.api"
      - "ApiSettings:OrderingUrl=http://ordering.api"
    ports:
      - "8005:80"

  webmvc:
    container_name: webmvc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiSettings:GatewayAddress=http://ocelotapigwweb"
    ports:
      - "8007:80"
