version: '3.4'

services:
  catalog.db:
    image: mongo

  basket.db:
    image: redis:alpine

  discount.db:
    image: postgres

  order.db:
    image: mcr.microsoft.com/mssql/server:2017-latest

  pgadmin:
    image: dpage/pgadmin4

  rabbitmq:
    image: rabbitmq:3-management-alpine

  portainer:
    image: portainer/portainer-ce

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    depends_on:
      - elasticsearch

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - catalog.db
      - elasticsearch
      - kibana
     
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    depends_on:
      - basket.db
      - rabbitmq
      - elasticsearch
      - kibana

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile
    depends_on:
      - discount.db
      - elasticsearch
      - kibana

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile
    depends_on:
      - discount.db
      - elasticsearch
      - kibana

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
    depends_on:
      - order.db
      - rabbitmq
      - elasticsearch
      - kibana

  ocelotapigw.web:
    image: ${DOCKER_REGISTRY-}ocelotapigwweb
    build:
      context: .
      dockerfile: ApiGateways/OcelotApiGw.Web/Dockerfile
    depends_on:
      - catalog.api
      - basket.api
      - discount.api
      - ordering.api

  ocelotapigw.mobile:
    image: ${DOCKER_REGISTRY-}ocelotapigwmobile
    build:
      context: .
      dockerfile: ApiGateways/OcelotApiGw.Mobile/Dockerfile
    depends_on:
      - catalog.api
      - basket.api
      - discount.api
      - ordering.api

  shopping.aggregator.mobile:
    image: ${DOCKER_REGISTRY-}shoppingaggregatormobile
    build:
      context: .
      dockerfile: ApiGateways/Mobile.Bff.Shopping/Shopping.Aggregator.Mobile/Dockerfile
    depends_on:
      - catalog.api
      - basket.api
      - ordering.api

  shopping.aggregator.web:
    image: ${DOCKER_REGISTRY-}shoppingaggregatorweb
    build:
      context: .
      dockerfile: ApiGateways/Web.Bff.Shopping/Shopping.Aggregator.Web/Dockerfile
    depends_on:
      - catalog.api
      - basket.api
      - ordering.api

  webmvc:
    image: ${DOCKER_REGISTRY-}webmvc
    build:
      context: .
      dockerfile: WebApps/WebMVC/Dockerfile
    depends_on:
      - ocelotapigw.web
      - catalog.api
      - basket.api
      - discount.api
      - ordering.api

networks:
  elastic:
    driver: bridge

volumes:
  mongo_data:
  elasticsearch_data:
  portainer_data:
  postgres_data:
  pgadmin_data:







