apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocelotapigwmobile-deployment
  labels:
    app: ocelotapigwmobile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocelotapigwmobile
  template:
    metadata:
      labels:
        app: ocelotapigwmobile
    spec:
      containers:
        - name: ocelotapigwmobile
          image: aspnetcoremicroservices.azurecr.io/ocelotapigwmobile:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ocelotapigwmobile-service
spec:
  type: NodePort
  selector:
    app: ocelotapigwmobile
  ports:
    - protocol: TCP
      port: 8011
      targetPort: 80
      nodePort: 34000